# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 08:23
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='摘要')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('create_at', models.DateTimeField(verbose_name='发布时间')),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='头像')),
            ],
            options={
                'verbose_name': '自我简介',
                'verbose_name_plural': '自我简介',
            },
        ),
        migrations.CreateModel(
            name='Ziyu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('create_at', models.DateTimeField(verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '喃喃自语',
                'verbose_name_plural': '喃喃自语',
            },
        ),
    ]
