# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 07:30
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='摘要')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('create_at', models.DateTimeField(verbose_name='发布时间')),
            ],
            options={
                'verbose_name_plural': '自我简介',
                'verbose_name': '自我简介',
            },
        ),
    ]
