# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 06:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ziyu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('create_at', models.DateTimeField(verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '喃喃自语',
                'verbose_name_plural': '喃喃自语',
            },
        ),
    ]
