# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ziyu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziyu',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='标题'),
        ),
    ]
