# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 07:20
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=125, verbose_name='标题')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='摘要')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('create_at', models.DateTimeField(verbose_name='发布时间')),
                ('update_at', models.DateTimeField(verbose_name='更新时间')),
                ('topped', models.BooleanField(default=False, verbose_name='置顶')),
            ],
            options={
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '分类',
                'verbose_name': '分类',
            },
        ),
        migrations.CreateModel(
            name='FriendlyLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('url', models.URLField(verbose_name='链接')),
                ('message', models.TextField(blank=True, verbose_name='备注')),
                ('create_at', models.DateTimeField(verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '友情链接',
                'verbose_name': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('message', models.TextField(verbose_name='留言')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='被评论文章')),
            ],
            options={
                'verbose_name_plural': '评论',
                'verbose_name': '评论',
            },
        ),
        migrations.CreateModel(
            name='Siteinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='网站标题')),
                ('icon', models.ImageField(upload_to='icon', verbose_name='网站图标')),
                ('pagesnum', models.IntegerField(default=8, verbose_name='一页文章数')),
            ],
            options={
                'verbose_name_plural': '网站信息',
                'verbose_name': '网站信息',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '标签',
                'verbose_name': '标签',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, max_length=100, to='blog.Tag', verbose_name='标签'),
        ),
    ]
