# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
    ]
