# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180601_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendlyLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('url', models.URLField(verbose_name='链接')),
                ('message', models.TextField(blank=True, verbose_name='备注')),
                ('create_at', models.DateTimeField(verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '友情链接',
                'verbose_name': '友情链接',
            },
        ),
    ]
